import "@/app/globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Next JS 14 Blog",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/icons/gitpot_logo.svg",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={roboto.variable}>
        <div className='wrapper'>{children}</div>
      </body>
    </html>
  );
}
